# Generated by Selenium IDE
# from selenium import webdriver
#
#
# class TestSearchTest():
#   def setup_method(self, method):
#     self.driver = webdriver.Chrome()
#     self.vars = {}
#
#   def teardown_method(self, method):
#     self.driver.quit()
#
#   def test_searchTest(self):
#     # Test name: Search Test
#     # 13 | click | css=.logo |
#     # Step # | name | target | value
#     # 1 | open | / |
#     self.driver.get("http://127.0.0.1:8000/")
#     # 2 | setWindowSize | 1848x1053 |
#     self.driver.set_window_size(1848, 1053)
#     # 3 | click | name=unit_name |
#     self.driver.find_element(By.NAME, "unit_name").click()
#     # 4 | type | name=unit_name | Mangudai
#     self.driver.find_element(By.NAME, "unit_name").send_keys("Mangudai")
#     # 5 | click | css=.search-icon |
#     self.driver.find_element(By.CSS_SELECTOR, ".search-icon").click()
#     # 6 | click | css=.logo |
#     self.driver.find_element(By.CSS_SELECTOR, ".logo").click()
#     # 7 | click | name=unit_name |
#     self.driver.find_element(By.NAME, "unit_name").click()
#     # 8 | type | name=unit_name | Mostafa
#     self.driver.find_element(By.NAME, "unit_name").send_keys("Mostafa")
#     # 9 | click | css=.search-icon |
#     self.driver.find_element(By.CSS_SELECTOR, ".search-icon").click()
#     # 10 | click | name=unit_name |
#     self.driver.find_element(By.NAME, "unit_name").click()
#     # 11 | type | name=unit_name | Archer
#     self.driver.find_element(By.NAME, "unit_name").send_keys("Archer")
#     # 12 | click | css=.search-icon |
#     self.driver.find_element(By.CSS_SELECTOR, ".search-icon").click()
#     self.driver.find_element(By.CSS_SELECTOR, ".logo").click()
#
#
#
from selenium import webdriver

import unittest
import HtmlTestRunner


class SearchTest(unittest.TestCase):
    result = unittest.TestResult()
    @classmethod
    def setUpClass(cls):
        cls.driver = webdriver.Chrome("/usr/bin/chromedriver")
        cls.driver.implicitly_wait(10)
        cls.driver.maximize_window()
    def test_success_search(self):
        self.driver.get("http://127.0.0.1:8000/")
        self.driver.find_element_by_name("unit_name").click()
        self.driver.find_element_by_name("unit_name").send_keys("Mangudai")
        self.driver.find_element_by_css_selector(".search-icon").click()
        self.driver.find_element_by_css_selector(".logo").click()

    def test_No_Data_found_for_search(self):
        self.driver.get("http://127.0.0.1:8000/")
        self.driver.find_element_by_name("unit_name").click()
        self.driver.find_element_by_name("unit_name").send_keys("Mostafa")
        self.driver.find_element_by_css_selector(".search-icon").click()
        self.driver.find_element_by_css_selector(".logo").click()



    @classmethod
    def tearDownClass(cls):
        cls.driver.close()
        cls.driver.quit()
        print("Test Completed")


if __name__ == '__main__':
    suite = unittest.TestLoader().loadTestsFromTestCase(SearchTest)
    test_result = unittest.TextTestRunner(verbosity=1).run(suite)
    print(test_result.wasSuccessful())
    unittest.main(testRunner=HtmlTestRunner.HTMLTestRunner(output='/home/elgohary/Work/AgeofEmpire/retriveApi/tests/Reports'))
    print(unittest.main())