# Generated by Django 3.1.7 on 2021-03-10 13:45

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('retriveApi', '0002_auto_20210310_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='attack_bonus',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
