# Generated by Django 3.1.7 on 2021-03-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retriveApi', '0003_auto_20210310_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='attack',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_id',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
