# Generated by Django 3.1.7 on 2021-03-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retriveApi', '0004_auto_20210310_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='range',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='accuracy',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='unit',
            name='blast_radius',
            field=models.FloatField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='unit',
            name='search_radius',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
