# Generated by Django 3.1.7 on 2021-03-10 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retriveApi', '0005_auto_20210310_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='blast_radius',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
