# Generated by Django 3.1.7 on 2021-03-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retriveApi', '0006_auto_20210310_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='accuracy',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='attack',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='range',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='search_radius',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
