# Generated by Django 3.1.7 on 2021-03-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retriveApi', '0007_auto_20210310_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='build_time',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='hit_points',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='line_of_sight',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='movement_rate',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='reload_time',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
